ALTER TABLE GAME
ADD(GATESIZE 	NUMBER(20),
HTSCORE 	NUMBER(10),
REFEREE 	CHAR(20));

CREATE TABLE GOAL
(GNO 		NUMBER(20),
PLAYER_ID	NUMBER(20),
GL_TIME		DATE);

INSERT INTO GOAL VALUES (1, 5, TO_DATE('12 12', 'HH24 MI'));
INSERT INTO GOAL VALUES (2, 6, TO_DATE('12 12', 'HH24 MI'));
INSERT INTO GOAL VALUES (3, 7, TO_DATE('12 12', 'HH24 MI'));
INSERT INTO GOAL VALUES (4, 8, TO_DATE('12 12', 'HH24 MI'));
 
CREATE TABLE PLAYER
(PLAYER_ID	NUMBER(20),
TNO		NUMBER(2),
SNAME		CHAR(20),
FNAME		CHAR(20));

INSERT INTO PLAYER VALUES (5, 1, 'Prince', 'Shrek');
INSERT INTO PLAYER VALUES (6, 1, 'Princess', 'Fiona');
INSERT INTO PLAYER VALUES (7, 2, 'Lord', 'Farquaad');
INSERT INTO PLAYER VALUES (8, 2, 'Rumplel', 'Stiltskin');

SELECT GAME_DATE, SNAME, FNAME, GL_TIME
FROM GAME, GOAL, PLAYER
WHERE GAME.GNO = GOAL.GNO
AND GOAL.PLAYER_ID = PLAYER.PLAYER_ID;
	

